/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import modelo3d from '../assets/models/modelos/model.glb'
export function Modelo(props) {
  const { nodes, materials } = useGLTF(modelo3d)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.chair.geometry} material={materials['Material.003']} position={[-1.49, 1.51, 0]} rotation={[0, -0.34, 0]} scale={[0.86, 1.02, 0.86]}>
        <mesh geometry={nodes.CHAIR_LEG.geometry} material={materials['Material.002']} position={[-0.99, -0.69, 0.84]} rotation={[-Math.PI / 2, -1.44, -Math.PI / 2]} scale={[0.03, 0.61, 0.03]} />
        <mesh geometry={nodes.CHAIR_LEG001.geometry} material={materials['Material.002']} position={[-0.99, -0.69, -0.84]} rotation={[-Math.PI / 2, -1.44, -Math.PI / 2]} scale={[0.03, 0.61, 0.03]} />
        <mesh geometry={nodes.CHAIR_LEG002.geometry} material={materials['Material.002']} position={[0.91, -0.69, 0.84]} rotation={[-Math.PI / 2, 1.44, Math.PI / 2]} scale={[0.03, 0.61, 0.03]} />
        <mesh geometry={nodes.CHAIR_LEG003.geometry} material={materials['Material.002']} color="#DCFF00" position={[0.91, -0.69, -0.84]} rotation={[-Math.PI / 2, 1.44, Math.PI / 2]} scale={[0.03, 0.61, 0.03]} />
      </mesh>
    </group>
  )
}

useGLTF.preload(modelo3d)
