/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Robot(props) {
  const { nodes, materials } = useGLTF('/robot.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.3, -2.1, 3]} rotation={[Math.PI / 2, 0, 3.2]} scale={0.002}>
        <mesh geometry={nodes.pCylinder1.geometry} material={materials['Mat.3']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder2.geometry} material={materials['Mat.3']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder3.geometry} material={materials['Mat.2']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder4.geometry} material={materials['Mat.2']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pPipe1.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pPipe2.geometry} material={materials['Mat.2']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pPipe3.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pPipe4.geometry} material={materials['Mat.2']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pSphere1.geometry} material={materials.initialShadingGroup} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pSphere2.geometry} material={materials.Mat} />
        <mesh geometry={nodes.pSphere3.geometry} material={materials.Mat} />
        <mesh geometry={nodes.pCylinder5.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder6.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder7.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder8.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder9.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder10.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder11.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder12.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder13.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCylinder14.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.Braso_1.geometry} material={materials['Mat.2']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.Braso_2.geometry} material={materials['Mat.2']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.Cuello.geometry} material={materials['Mat.001']} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCube1.geometry} material={materials.Mat} position={[188.24, 0, 130.77]} />
        <mesh geometry={nodes.pCube2.geometry} material={materials.initialShadingGroup} position={[188.24, 0, 130.77]} />
        <group position={[188.24, 0, 130.77]}>
          <mesh geometry={nodes.Malla014.geometry} material={materials.Mat} />
          <mesh geometry={nodes.Malla014_1.geometry} material={materials['Mat.1']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/robot.gltf')
