/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sillaverde(props) {
  const { nodes, materials } = useGLTF('/sillaverde.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.GreenChair_01.geometry} material={materials.GreenChair_01} position={[1.5, -1.2, 3]} />
    </group>
  )
}

useGLTF.preload('/sillaverde.gltf')
