/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Silla1_new(props) {
  const { nodes, materials } = useGLTF('/silla1_new.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} scale={[0.03, 0.6, 0.04]} position={[3, -2, 0.8]} rotation={[6, 3.5, 0]}/>
    </group>
  )
}

useGLTF.preload('/silla1_new.gltf')
